language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - rustup target list | grep '(default)' | awk '{print $1}'
  - cargo build --verbose --all
  - cargo test --verbose --all
  - RUST_BACKTRACE=1 cargo run --example compare
os:
  - linux
  - osx
  - windows
